### ISSUE TITLE
Sysvad driver install freeze

### ISSUE THREAD

**Issue by redaf** [redwork321/redwork321.github.io#1]
Hi redwork321,

I'm currently developing a virtual audio driver for Windows, and I saw that I'm experiencing the same issue than you did almost 3 years ago:

https://github.com/microsoft/Windows-driver-samples/issues/229

My problem is even worse, not only my target computer froze while installing the driver, but it won't reboot properly. My guess is that the driver was actually installed and Windows is bringing it up at startup, corrupting the system startup...

I press Shift+F8 before Windows startup to bring the Troubleshoot mode, which works fine, but whatever "Advanced option" I choose next asks to choose an account. There is my personal account, and the WDKRemoteUser. I can't connect to my personal account anymore: "The password is incorrect. Try again" (checked the keyboard layout, and made password visible, I'm 100% sure it is correct), also can't connect to WDKRemoteUser account because it is supposed to have no password...

Did you experience the same problem(s) ? Do you have any idea how I could fix this ?

I will definitely use a VM from now on...

Thanks for your help :)

**Comment by redwork321** [comment]
Oh hello there,
Unfortunately, I was not able to stabilize a dev environment back then :persevere:, and I moved on. So, no idea how to fix that!
Good luck with your developments!
